from __future__ import annotations

import re

# Generated from the supplied TvC wiki move pages.
# Mission Mode uses this only for command hints and input safeguards.
WIKI_INPUT_CATALOG = {
    'alex': (
        ('drop kick snapback', '46X+623C'),
        ('air powerbomb air', 'AIR 63214X'),
        ('flash chop suplex', '236X'),
        ('hyperbomb forward', '360'),
        ('stun gun headbutt', '421L+M'),
        ('suplex hyper bomb', '360'),
        ('machine gun chop', '236 HOLD C'),
        ('boomerang raid', '236XX'),
        ('hyperbomb back', '360'),
        ('stungun close', '421L+M'),
        ('air stampede', '28X'),
        ('charged chop', '236 HOLD C'),
        ('elbow slash', '[4]6X'),
        ('elbow', '[4]6X'),
        ('slash elbow', '[4]6X'),
        ('flash chop', '236X'),
        ('hyper bomb', '360'),
        ('knee smash', '623X'),
        ('wild stomp', '[2]8X'),
        ('hyperbomb', '360'),
        ('knee drop', '623X'),
        ('powerbomb', 'AIR 63214X'),
        ('air bomb', 'AIR 63214X'),
        ('dropkick', '46X+623C'),
        ('stampede', '28X'),
        ('stungun', '421L+M'),
        ('air b', 'JB'),
        ('air c', 'JC'),
        ('bomb', 'AIR 63214X'),
        ('chop', '236 HOLD C'),
        ('air', 'JB'),
    ),
    'batsu ichimonji': (
        ('heavy shooting star kick air', 'AIR 214A / AIR 214B / AIR 214C'),
        ('light shooting star kick air', 'AIR 214A / AIR 214B / AIR 214C'),
        ('mid shooting star kick air', 'AIR 214A / AIR 214B / AIR 214C'),
        ('air super guts bullet air', 'AIR 236XX'),
        ('heavy shooting star kick', 'AIR 214A / AIR 214B / AIR 214C'),
        ('light shooting star kick', 'AIR 214A / AIR 214B / AIR 214C'),
        ('mid shooting star kick', 'AIR 214A / AIR 214B / AIR 214C'),
        ('air super guts bullet', 'AIR 236XX'),
        ('united by fate bullet', '63214XX'),
        ('united by fate upper', '63214XX'),
        ('air guts bullet air', 'AIR 236X'),
        ('united by fate kick', '63214XX'),
        ('super guts bullet', 'AIR 236XX'),
        ('super guts upper', '623XX'),
        ('tardy counter 6b', '6B'),
        ('tardy counter 6c', '6C'),
        ('ground fireball', '236X'),
        ('divekick heavy', 'AIR 214A / AIR 214B / AIR 214C'),
        ('divekick light', 'AIR 214A / AIR 214B / AIR 214C'),
        ('united by fall', '63214XX'),
        ('crescent kick', '214X'),
        ('tardy counter', '6B'),
        ('air fireball', 'AIR 236X'),
        ('divekick mid', 'AIR 214A / AIR 214B / AIR 214C'),
        ('guts bullet', 'AIR 236X'),
        ('guts upper', '623X'),
        ('fireball', 'AIR 236X'),
        ('air a', 'JA'),
        ('air', 'JA'),
    ),
    'casshan': (
        ('air shooting star kick', 'AIR 236X'),
        ('super destruction beam', '421XX'),
        ('cash destruction beam', '421XX'),
        ('shooting star kick', 'AIR 236X'),
        ('cash boulder chop', '623X'),
        ('cash friender a', '63214X'),
        ('cash brutal ax', '623XX'),
        ('cash divekick', 'AIR 236X'),
        ('cash friender', '63214X'),
        ('catapult knee', '421X'),
        ('friender call', '63214X'),
        ('scrap android', '41236XX'),
        ('boulder chop', '623X'),
        ('denkou punch', '236X'),
        ('cash denkou', '236X'),
        ('cash air b', 'AIR B'),
        ('cash air c', 'AIR C'),
        ('cash scrap', '41236XX'),
        ('brutal ax', '623XX'),
        ('cash knee', '421X'),
        ('cash air', 'AIR B'),
        ('cash 2a', '2A'),
        ('cash 2b', '2B'),
        ('cash 2c', '2C'),
        ('cash 3c', '3C'),
        ('cash 5a', '5A'),
        ('cash 5b', '5B'),
        ('cash 5c', '5C'),
        ('cash 6b', '6B'),
        ('cash ja', 'AIR A'),
        ('cash b', 'AIR B'),
        ('cash c', 'AIR C'),
    ),
    'chun li': (
        ('shichisei senkukyaku air', 'AIR 236XX'),
        ('shichisei senkukyaku', 'AIR 236XX'),
        ('spinning bird kick', '28X'),
        ('hyakuretsukyaku', 'MASH X'),
        ('lightning legs', 'MASH X'),
        ('tenshohyaku', '623X'),
        ('tenshokyaku', '623X'),
        ('hoyokusen', '623XX'),
        ('kikikosho', '236XX'),
        ('kikoken', '41236X'),
        ('kikosho', '236XX'),
        ('hyaku', 'MASH X'),
        ('level', 'AIR 236XX'),
        ('hoyo', '623XX'),
        ('legs', 'MASH X'),
        ('j2b', 'J2B'),
        ('jcc', 'JC > JC'),
        ('sbk', '28X'),
    ),
    'doronjo': (
        ('breakdance', '2C'),
        ('pummel', '236A'),
        ('taunt', 'TAUNT(T)'),
        ('doro in the beginning', '236XX'),
        ('doro rock abandon air', 'AIR 214X'),
        ('aizuwakamatzu punch', '236X'),
        ('punching bag fiesta', '214XX'),
        ('doro comfy launch', '22 > C'),
        ('doro punching bag', '214XX'),
        ('doro rock abandon', 'AIR 214X'),
        ('supreme evil plan', '623XX'),
        ('in the beginning', '236XX'),
        ('doro comfy spin', '22 > 2C'),
        ('piglet flare up', '623X'),
        ('naniwa clutch', '421X'),
        ('doro supreme', '623XX'),
        ('rock abandon', 'AIR 214X'),
        ('doro clutch', '421X'),
        ('doro comfy', '22'),
        ('doro punch', '236X'),
        ('doron spin', '22 > 2C'),
        ('doro tree', '623X'),
        ('doronsalt', '22 > C'),
        ('get comfy', '22'),
        ('doro 2a', '2A'),
        ('doro 2b', '2B'),
        ('doro 2c', '2C'),
        ('doro 3c', '3C'),
        ('doro 5a', '5A'),
        ('doro 5b', '5B'),
        ('doro 5c', '5C'),
        ('doro ja', 'AIR A'),
        ('doro jb', 'AIR B'),
        ('doro jc', 'AIR C'),
    ),
    'frank west': (
        ('giant big bad explosion', '623XX'),
        ('the real megabuster', '236XX'),
        ('bid bad explosion', '623XX'),
        ('round house kick', '46X'),
        ('roundhouse kick', '46X'),
        ('zombie charge', '623XX'),
        ('dead risiing', '63214XX'),
        ('for infinite', '3C / 3C63214X'),
        ('zombie spree', '421X'),
        ('3c infinite', '3C / 3C63214X'),
        ('dead rising', '63214XX'),
        ('giant swing', '63214X'),
        ('grand slam', '236X'),
        ('zombie a', '623A / 623B / 623C'),
        ('zombie b', '623A / 623B / 623C'),
        ('zombie c', '623A / 623B / 623C'),
        ('dodge a', '22A / 22B / 22C'),
        ('dodge b', '22A / 22B / 22C'),
        ('dodge c', '22A / 22B / 22C'),
        ('zombie', '623A / 623B / 623C'),
        ('dodge', '22A / 22B / 22C'),
        ('j2c', 'J2C'),
    ),
    'gold lightan': (
        ('finger crash gold crash', '236XX'),
        ('battleship snapback', '63214A / 63214B / 63214C'),
        ('battleship breaker', '63214A / 63214B / 63214C'),
        ('finger crash', '236XX'),
        ('battleship', '63214A / 63214B / 63214C'),
        ('gold crash', '41236XX'),
        ('gold press', '360C'),
        ('gold quake', '22X'),
        ('tank slice', '41236X'),
        ('gold kick', '63214XX'),
        ('snapback', '63214A / 63214B / 63214C'),
    ),
    'ippatsu': (
        ('run out of meter', 'AB / 8A8B / 2A2B / C'),
        ('rainball a air', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('rainball b air', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('rainball c air', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('gya activate', 'AB / 8A8B / 2A2B / C'),
        ('mround blast', '214X'),
        ('straight fly', '46X'),
        ('mound blast', '214X'),
        ('quick upper', '623X'),
        ('activation', 'AB / 8A8B / 2A2B / C'),
        ('grand slam', '63214XX'),
        ('rainball a', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('rainball b', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('rainball c', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('gya punch', 'AB / 8A8B / 2A2B / C'),
        ('gya sword', 'AB / 8A8B / 2A2B / C'),
        ('gya slam', 'AB / 8A8B / 2A2B / C'),
        ('rainball', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('gya end', 'AB / 8A8B / 2A2B / C'),
        ('final', '623XX'),
        ('gya c', 'AB / 8A8B / 2A2B / C'),
        ('air', '236A / 236B / 236C / AIR 236A / AIR 236B / AIR 236C'),
        ('gya', 'AB / 8A8B / 2A2B / C'),
    ),
    'joe the condor': (
        ('cactus bunker file joe counter webm thumb center the animation capcom doesn t want you to see', '214X'),
        ('kagaku ninpo tatsumaki fighter', '63214XX'),
        ('air condor magnum air', 'AIR 236XX'),
        ('shuriken feather air', 'HOLD X > RELEASE X'),
        ('bird missile strike', '623XX'),
        ('shuriken feather', 'HOLD X > RELEASE X'),
        ('savage shot air', 'AIR 623X'),
        ('battering ram', '236X'),
        ('condor magnum', 'AIR 236XX'),
        ('shuriken air', 'HOLD X > RELEASE X'),
        ('bird missle', '623XX'),
        ('savage shot', 'AIR 623X'),
        ('magnum air', 'AIR 236XX'),
        ('savage air', 'AIR 623X'),
        ('wild lasso', '46A'),
        ('shuriken', 'HOLD X > RELEASE X'),
        ('cactus', '63214X'),
        ('magnum', 'AIR 236XX'),
        ('savage', 'AIR 623X'),
        ('tatsu', '63214XX'),
    ),
    'jun the swan': (
        ('science ninpo phoenix', '214XX'),
        ('lightning kick b', '623X'),
        ('lightning kick', '623X'),
        ('swan rush air', 'AIR 421X'),
        ('dancing swan', '421X'),
        ('lightning a', '623X'),
        ('mirage swan', '421XX'),
        ('talon burst', '236XX'),
        ('lightning', '623X'),
        ('swan rush', 'AIR 421X'),
        ('bingo', '214X'),
        ('rush', 'AIR 421X'),
        ('yoyo', '236X'),
    ),
    'kaijin no soki': (
        ('oni cutter after oni mode with 7 red orbs absorbed', '623XX'),
        ('absorb hold while in oni mode', '63214XX / P'),
        ('sokisword of purification', '236XX'),
        ('sokiheadsplitter issen', '41236X / 41236X > B+C'),
        ('sokioni tactics issen', '623XX'),
        ('sword of purification', '236XX'),
        ('deflect mid high hit', '63214X'),
        ('sokishoulder tackle', '623X'),
        ('headsplitter issen', '41236X / 41236X > B+C'),
        ('sokioni activation', '63214XX / P'),
        ('sokideflect issen', '63214X'),
        ('sokiheadsplitter', '41236X / 41236X > B+C'),
        ('sokioni tactics', '623XX'),
        ('sokioni cutter', '623XX'),
        ('headsplitter', '41236X / 41236X > B+C'),
        ('soki6c issen', '6C / 6CB+C'),
        ('sokifinisher', '22C'),
        ('oni tactics', '623XX'),
        ('sokideflect', '63214X'),
        ('sokiabsorb', '63214XX / P'),
        ('finisher', '22C'),
        ('oni mode', '63214XX / P'),
        ('deflect', '63214X'),
        ('soki2a', '2A'),
        ('soki2b', '2B'),
        ('soki2c', '2C'),
        ('soki3c', '3C'),
        ('soki5a', 'A'),
        ('soki5b', '5B'),
        ('soki5c', '5C'),
        ('soki6c', '6C / 6CB+C'),
        ('sokija', 'JA'),
        ('sokijb', 'JB'),
        ('sokijc', 'JC'),
        ('issen', 'B+C'),
        ('slam', '623X'),
    ),
    'karas': (
        ('ukifune', '236'),
        ('kasha overhead', '6X'),
        ('super hiei zangetsu', '63214XX'),
        ('tobimizuchi', '63214X'),
        ('6c unblock', 'HOLD6C'),
        ('karaskasha', '46X'),
        ('super hiei', '63214XX'),
        ('yasagurama', '46X > 236X > 6C'),
        ('narukami', '623X'),
        ('shiranui', '623XX'),
        ('ungaikyo', '236X'),
        ('zaneijin', '236X > 236XX'),
        ('tobi 4a', '63214X / 62314X > 236X / 62314X > 214A / 62314X > 214B / 62314X > 214C'),
        ('tobi 4b', '63214X / 62314X > 236X / 62314X > 214A / 62314X > 214B / 62314X > 214C'),
        ('tobi 4c', '63214X / 62314X > 236X / 62314X > 214A / 62314X > 214B / 62314X > 214C'),
        ('tobi 6x', '63214X / 62314X > 236X / 62314X > 214A / 62314X > 214B / 62314X > 214C'),
        ('yoinagi', '46C'),
        ('kasha', '[4]6X'),
        ('tobi', '63214X / 62314X > 236X / 62314X > 214A / 62314X > 214B / 62314X > 214C'),
        ('yato', '46X > 236X > 46X'),
    ),
    'ken the eagle': (
        ('air bird smash', 'XX'),
        ('bird smash', 'XX'),
        ('random flight', '421X'),
        ('bird shoot a', '623X'),
        ('bird shoot b', '623X'),
        ('bird shoot c', '623X'),
        ('bird shoot', '623X'),
        ('bird run', '46X'),
    ),
    'megaman volnutt': (
        ('max power drill uppercut', '623XX'),
        ('max power shining laser', '236XX'),
        ('weapon change forward', '22X / 214X / 236X'),
        ('weapon change neutral', '22X / 214X / 236X'),
        ('weapon change back', '22X / 214X / 236X'),
        ('machine gun sweep', '214XX'),
        ('drill uppercut', '623XX'),
        ('shining laser', '236XX'),
        ('weapon change', '22X / 214X / 236X'),
        ('megabuster', 'HOLDC'),
        ('5c charge', 'HOLDC'),
        ('6b shield', '6B'),
        ('3b drill', '3B'),
        ('6b drill', '6B'),
        ('6b fist', '6B'),
        ('jc spam', 'AIR C / AIR C214X236XAIR C / 7 / 8 / 9 > IADAIR C'),
        ('3b gun', '3B'),
        ('6b gun', '6B'),
        ('spam', 'AIR C / AIR C214X236XAIR C / 7 / 8 / 9 > IADAIR C'),
    ),
    'morrigan aensland': (
        ('darkmess illusion ground', '421XX / AIR 421XX'),
        ('darkness illusion air', '421XX / AIR 421XX'),
        ('valkyrie turn attack', '63214XX / 63214XX > X'),
        ('darkmess illusion', '421XX / AIR 421XX'),
        ('darkness illusion', '421XX / AIR 421XX'),
        ('finishing shower', '236XX'),
        ('soul fist ground', '236X'),
        ('shell kick air', 'AIR 214C'),
        ('tvcmorrigan6b', '6B'),
        ('valkyrie turn', '63214XX / 63214XX > X'),
        ('shadow blade', '623X'),
        ('vector drain', '63214X'),
        ('shell kick', 'AIR 214C'),
        ('soul fist', '236X'),
        ('attack', '63214XX / 63214XX > X'),
        ('air', '421XX / AIR 421XX'),
    ),
    'polimar': (
        ('poli hurricane destruction fist', '46X'),
        ('illusive destructive fist', '236XX'),
        ('single handed vacuum spin', '360'),
        ('3 stage reaction kick', '623X > X > 214X'),
        ('tenshin polimar drill', 'A+B > A+B > B+C'),
        ('poli tenshin drill', 'A+B > A+B > B+C'),
        ('razor chain kicks', '236X'),
        ('poli storm kanae', '214X'),
        ('poli razor kick', '236X'),
        ('poli hurricane', '360XX'),
        ('poli illusive', '236XX'),
        ('storm kamae', '214X'),
        ('poli stage', '623X > X > 214X'),
        ('poli 2a', '2A'),
        ('poli 2b', '2B'),
        ('poli 2c', '2C'),
        ('poli 3c', '3C'),
        ('poli 5a', 'A'),
        ('poli 5b', 'B'),
        ('poli 5c', 'C'),
        ('poli 6b', '6B'),
        ('poli 6c', '6C'),
        ('poli ja', 'JA'),
        ('poli jb', 'JB'),
        ('poli jc', 'JC'),
    ),
    'roll': (
        ('bucket', '623X'),
        ('roll broom swing charged', '236X'),
        ('roll splash charged', '214X > 623X'),
        ('no you didn t otg', '623X'),
        ('roll mop up turbo', '46XX'),
        ('oh no you didn t', '623X'),
        ('roll broom swing', '236X'),
        ('mop up standing', '46 CHARGE X'),
        ('puddle charged', '214X > 623X'),
        ('roll down time', '214XX'),
        ('roll power up', '214X'),
        ('swing charged', '236X'),
        ('no you didnt', '623X'),
        ('mop up mash', '46XX'),
        ('roll mop up', '46 CHARGE X'),
        ('roll splash', '214X > 623X'),
        ('heal self', '214XX'),
        ('charge', '214X'),
        ('puddle', '214X > 623X'),
        ('swing', '236X'),
        ('otg', '46XX'),
    ),
    'ryu': (
        ('shinku tatsumaki senpukyaku', '214XX'),
        ('joudan sokutogeri', '421X'),
        ('air hadouken air', 'AIR 236X'),
        ('shinkuu hadouken', '236XX'),
        ('shin shoryuken', '623XX'),
        ('tatsu ground', '214X'),
        ('shin shoryu', '623XX'),
        ('tatsu super', '214XX'),
        ('shoryuken', '623X'),
        ('tatsumaki', '214X'),
        ('air hado', 'AIR 236X'),
        ('hadouken', 'AIR 236X'),
        ('shinkuu', '236XX'),
        ('donkey', '421X'),
        ('shoryu', '623X'),
        ('tatsu', '214X'),
        ('hado', 'AIR 236X'),
    ),
    'saki omokane': (
        ('load super armor piercing shell', '63214XX / 63214XX > C'),
        ('world s greatest attack', '623XX'),
        ('worlds greatest attack', '623XX'),
        ('super ammo load shot', '63214XX / 63214XX > C'),
        ('super bullet load', '63214XX / 63214XX > C'),
        ('positron cannon', '41236X'),
        ('grenade ground', '421X'),
        ('positron storm', '236XX'),
        ('grenade toss', '421X'),
        ('special ammo', '22A / 22B / 22C'),
        ('ammo load a', '22A / 22B / 22C'),
        ('ammo load b', '22A / 22B / 22C'),
        ('ammo load c', '22A / 22B / 22C'),
        ('ammo load', '22A / 22B / 22C'),
        ('headbutt', '63214X'),
        ('grenade', '421X'),
    ),
    'tekkaman': (
        ('super spinning tek lancer', '623XX'),
        ('space knights formation', '214XX'),
        ('file currently missing', '3C'),
        ('tek voltekka unarmed', '236XX'),
        ('tek galaxy windmill', '[2]8X'),
        ('tek voltekka ground', '236XX'),
        ('tek space knight', '214XX'),
        ('tek spinning tek', '623XX'),
        ('tek voltekka air', '236XX'),
        ('galaxy windmill', '[2]8X'),
        ('tekk 2a unarmed', '2A'),
        ('tekk 2c unarmed', '2C'),
        ('tekk 5b unarmed', 'B'),
        ('tekk 5c unarmed', 'C'),
        ('tekk ja unarmed', 'JA'),
        ('tekk jc unarmed', 'JC'),
        ('tek voltekka', '236XX'),
        ('tvc tekk j2c', 'J.2C'),
        ('tek gatling', 'MASH X'),
        ('tek lance a', '46X'),
        ('tek lancer', '46X'),
        ('tek lance', '46X'),
        ('tek win a', '214X'),
        ('voltekka', '236XX'),
        ('gatling', 'MASH X'),
        ('tek win', '214X'),
        ('tekk 2a', '2A'),
        ('tekk 2b', '2B'),
        ('tekk 2c', '2C'),
        ('tekk 3c', '3C'),
        ('tekk 5a', 'A'),
        ('tekk 5b', 'B'),
        ('tekk 5c', 'C'),
        ('tekk 6c', '6C'),
        ('tekk ja', 'JA'),
        ('tekk jb', 'JB'),
        ('tekk jc', 'JC'),
        ('unarmed', '236XX'),
        ('center', '2C'),
        ('tekwin', '214X'),
        ('air', '236XX'),
    ),
    'tekkaman blade': (
        ('air baselard', '236X'),
        ('baselard', '236X'),
        ('blitz', '[2]8X'),
        ('omnidirectional super voltekka', '63214XX'),
        ('crash intrude', '236XX'),
        ('charge b', 'A / B / C'),
        ('charge c', 'A / B / C'),
        ('falchion', '214X'),
        ('shamshir', 'MASH X'),
        ('voltekka', '623XX'),
        ('b base', 'A / B / C'),
        ('base h', 'A / B / C'),
        ('base l', 'A / B / C'),
        ('charge', 'A / B / C'),
        ('crash', '236XX'),
        ('omni', '63214XX'),
        ('j2c', 'J.2C'),
    ),
    'viewtiful joe': (
        ('dolphin jit64 dc direct3d hle fps vps tatsunoko vs capcom ultimate all stars', '6B+C'),
        ('joesazfixedreally', '214XX'),
        ('vjoe red hot kick', 'AIR 214X'),
        ('red hot kick air', 'AIR 214X'),
        ('vjoe voom charge', 'HOLD236X'),
        ('vjoe voomerang b', '236A / 236B / 236C'),
        ('vjoe mach speed', '623XX'),
        ('vjoe desperado', '236XX'),
        ('vjoe voomerang', '236A / 236B / 236C'),
        ('shocking pink', '214X'),
        ('slow and zoom', '214XX'),
        ('red hot kick', 'AIR 214X'),
        ('vjoe air joe', 'MASH X'),
        ('air joe air', 'MASH X'),
        ('vjoe voom a', '236A / 236B / 236C'),
        ('vjoe voom c', '236A / 236B / 236C'),
        ('hero taunt', '6B+C'),
        ('mach speed', '623XX'),
        ('vjoe shock', '214X'),
        ('desperado', '236XX'),
        ('vjoe voom', '236A / 236B / 236C'),
        ('voomerang', '236A / 236B / 236C'),
        ('vjoe joe', 'MASH X'),
        ('vjoe 2a', '2A'),
        ('vjoe 2b', '2B'),
        ('vjoe 2c', '2C'),
        ('vjoe 3c', '3C'),
        ('vjoe 5a', '5A'),
        ('vjoe 5b', '5B'),
        ('vjoe 5c', '5C'),
        ('vjoe 6b', '6B'),
        ('vjoe ja', 'AIR A'),
        ('vjoe jb', 'AIR B'),
        ('vjoe jc', 'AIR C'),
        ('joe', 'MASH X'),
    ),
    'yatterman 1': (
        ('yatter hop', 'B'),
        ('this week s surprise robots', '623XX'),
        ('yatterwan special attack', '236XX'),
        ('y1 this week s robots', '623XX'),
        ('y1 yatterwan special', '236XX'),
        ('y1 yatter spin b', '623X / 623A / 623B / 623C'),
        ('yatter wan flame', '214XX'),
        ('y1 yatter flame', '214XX'),
        ('y1 yatter run c', '214X / A / B / C'),
        ('y1 yatterspin a', '623X / 623A / 623B / 623C'),
        ('y1 yatterspin c', '623X / 623A / 623B / 623C'),
        ('y1 yatter spin', '623X / 623A / 623B / 623C'),
        ('y1 yatterrun a', '214X / A / B / C'),
        ('y1 yatterrun b', '214X / A / B / C'),
        ('y1 yattershock', '[4]6X'),
        ('y1 kendamagic', '236X'),
        ('y1 yatter run', '214X / A / B / C'),
        ('y1 yatterspin', '623X / 623A / 623B / 623C'),
        ('y1 yatterrun', '214X / A / B / C'),
        ('yattershock', '[4]6X'),
        ('kendamagic', '236X'),
        ('y1 2a', '2A'),
        ('y1 2b', '2B'),
        ('y1 2c', '2C'),
        ('y1 3c', '3C'),
        ('y1 5a', 'A'),
        ('y1 5b', 'B'),
        ('y1 5c', 'C'),
        ('y1 6b', '6B'),
        ('y1 6c', '6C'),
        ('y1 ja', 'JA'),
        ('y1 jb', 'JB'),
        ('y1 jc', 'JC'),
    ),
    'yatterman 2': (
        ('this week s special robots', '214XX'),
        ('omochama', '623XX'),
        ('this week s surprise robots', '214XX'),
        ('super passion level 1', '236XX'),
        ('y2 yatterswing a', 'A / B / C'),
        ('y2 yatterswing b', 'A / B / C'),
        ('y2 yatterswing c', 'A / B / C'),
        ('y2 yattershield', '214X'),
        ('y2 yattersplash', 'MASH X'),
        ('y2 yatterstep a', 'A'),
        ('y2 yatterstep b', 'B'),
        ('y2 yatterstep c', 'C'),
        ('y2 yatterswing', 'A / B / C'),
        ('y2 yatterstep', '236X'),
        ('y2 this week', '214XX'),
        ('yattershield', '214X'),
        ('yattersplash', 'MASH X'),
        ('y2 passion3', '236XX'),
        ('y2 passion', '236XX'),
        ('yatterstep', '236X'),
        ('omotchama', '623XX'),
        ('y2 omoch', '623XX'),
        ('level 2', '236XX'),
        ('level 3', '236XX'),
        ('y2 j c', 'HOLDJC'),
        ('y2 2a', '2A'),
        ('y2 2b', '2B'),
        ('y2 2c', '2C'),
        ('y2 3b', '3B'),
        ('y2 3c', '3C'),
        ('y2 5a', 'A'),
        ('y2 5b', 'B'),
        ('y2 ja', 'JA'),
        ('y2 jb', 'JB'),
        ('y2 jc', 'JC'),
        ('y2 c', 'HOLD2C'),
        ('y2 j', 'HOLDJC'),
        ('y25c', 'C'),
    ),
    'zero': (
        ('hyper zero blaster', 'HOLD X'),
        ('sentsuizan air', 'AIR 236X'),
        ('sug activate', '214XX'),
        ('sug example', '214XX'),
        ('hado light', '46X'),
        ('sentsuizan', 'AIR 236X'),
        ('teleport a', '214A / B'),
        ('dark hold', '623XX'),
        ('dive kick', 'AIR 236X'),
        ('hadangeki', '46X'),
        ('hienkyaku', '214A / B'),
        ('ryuenjin', '623X'),
        ('sougenmu', '214XX'),
        ('teleport', '214A / B'),
        ('rekkoha', '236XX'),
        ('buster', 'HOLD X'),
        ('shoryu', '623X'),
        ('thumb', '214XX'),
        ('rek', '236XX'),
    ),
}

CHARACTER_ALIASES = {'chunli': 'chun li', 'chun li': 'chun li', 'morrigan': 'morrigan aensland', 'soki': 'kaijin no soki', 'kaijin no soki': 'kaijin no soki', 'volnutt': 'megaman volnutt', 'mega man volnutt': 'megaman volnutt', 'megaman volnutt': 'megaman volnutt', 'saki': 'saki omokane', 'ippatsuman': 'ippatsu', 'joe': 'joe the condor', 'jun': 'jun the swan', 'ken': 'ken the eagle', 'blade': 'tekkaman blade', 'yatterman 1': 'yatterman 1', 'yatterman 2': 'yatterman 2'}


def _normalize(value: str) -> str:
    value = str(value or '').lower().replace('j.', ' air ')
    value = re.sub(r'[^a-z0-9]+', ' ', value)
    return ' '.join(value.split())


def _character_key(character_name: str) -> str:
    key = _normalize(character_name)
    if key in CHARACTER_ALIASES:
        return CHARACTER_ALIASES[key]
    if key in WIKI_INPUT_CATALOG:
        return key
    for candidate in WIKI_INPUT_CATALOG:
        if key and (key in candidate or candidate in key):
            return candidate
    return key


_STRENGTH_BUTTONS = {
    "a": "A",
    "b": "B",
    "c": "C",
    "l": "A",
    "light": "A",
    "weak": "A",
    "m": "B",
    "mid": "B",
    "medium": "B",
    "h": "C",
    "heavy": "C",
    "strong": "C",
}

_STRENGTH_WORDS = frozenset(_STRENGTH_BUTTONS)


def _strength_button(candidates: list[str]) -> str:
    for raw in reversed(candidates):
        tokens = re.findall(r"[A-Za-z]+", str(raw or "").lower())
        for token in reversed(tokens):
            mapped = _STRENGTH_BUTTONS.get(token)
            if mapped:
                return mapped
    return ""


def _without_strength(value: str) -> str:
    tokens = [
        token
        for token in _normalize(value).split()
        if token not in _STRENGTH_WORDS
    ]
    return " ".join(tokens)


def infer_wiki_input_notation(character_name: str, candidates: list[str]) -> str:
    entries = WIKI_INPUT_CATALOG.get(_character_key(character_name), ())
    if not entries:
        return ""

    normalized_candidates = [
        _normalize(candidate) for candidate in candidates if _normalize(candidate)
    ]
    if not normalized_candidates:
        return ""

    candidate_forms: list[tuple[str, str]] = []
    for candidate in normalized_candidates:
        base = _without_strength(candidate)
        candidate_forms.append((candidate, base))

    best_score = -1
    best_alias = ""
    best_notation = ""

    for alias, notation in entries:
        alias_tokens = set(alias.split())
        for candidate, base in candidate_forms:
            score = -1

            if alias == candidate:
                score = 1000 + len(alias)
            elif base and alias == base:
                score = 950 + len(alias)
            elif alias in candidate or candidate in alias:
                score = 800 + min(len(alias), len(candidate))
            elif base and (alias in base or base in alias):
                score = 750 + min(len(alias), len(base))
            elif base:
                base_tokens = set(base.split())
                meaningful = {
                    token for token in base_tokens
                    if len(token) >= 4
                }
                if meaningful and meaningful.issubset(alias_tokens):
                    score = 600 + sum(len(token) for token in meaningful)

            if score > best_score or (
                score == best_score and len(alias) > len(best_alias)
            ):
                best_score = score
                best_alias = alias
                best_notation = notation

    if not best_notation:
        return ""

    strength = _strength_button(candidates)
    if strength:
        # Replace a single wildcard strength, but preserve XX supers.
        best_notation = re.sub(r"(?<!X)X(?!X)", strength, best_notation)

    return best_notation
