[project]
name = "tvc-tools"
version = "0.1.0"
dependencies = ["dolphin-memory-engine"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["tvc_tools"]
